name: Setup Node Project
description: 'Composite action for setting up a node project with pnpm, caching, and dependencies installation'

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: pnpm

    - name: Install
      run: pnpm install
      shell: bash

    - name: Install Playwright
      run: pnpm exec playwright install --with-deps --only-shell
      shell: bash
      working-directory: apps/angelblanco.dev
