# Invoked via: /git:commit
description = "Execute a git commit -am command with message that starts with an emoji and meaningful, detailed, message based on current diff file content from latest commit"
prompt = """
Please generate a Conventional Commit message based on the following git diff.

```diff
!{git diff --staged}
```

The commit message should start with an emoji and be detailed and meaningful.
Save the commit message to a file named `./git-commit-message.txt` in the root of the repo.
Finally, run `git commit -a -F ./git-commit-message.txt` to create the commit.
"""
