# Invoked via: /git:commit
description = "Execute a git commit -am command with message that starts with an emoji and meaningful, detailed, message based on current diff file content from latest commit"
prompt = """

Please generate a git commit -am command with Conventional Commit message based on the following git diff.
The commit message should start with an emoji and be detailed and meaningful.

```diff
!{git diff --staged}
```
"""
