name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: [CI]
    types:
      - completed
    branches:
      - master
env:
  NUXT_PUBLIC_SCRIPTS_GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.workflow_run && github.event.workflow_run.conclusion == 'success') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Cache Turbo Build
        uses: actions/cache@v4
        with:
          path: /..turbo
          key: ${{ runner.os }}-turbo-deploy-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-deploy

      - name: Setup Node Project
        uses: ./.github/actions/setup-node-project

      - name: Nuxt prerender
        run: pnpm build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./apps/angelblanco.dev/.output/public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
