name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: [CI]
    types:
      - completed
    branches:
      - master

jobs:
  env:
    NUXT_PUBLIC_SCRIPTS_GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'production' }}
    # Only run if the CI workflow was successful or if manually triggered
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.workflow_run && github.event.workflow_run.conclusion == 'success') }}

    steps:
      - name: Setup Node Project
        uses: ./.github/actions/setup-node-project

      - name: Build
        run: pnpm build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./apps/angelblanco.dev/.output/public
