name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: [CI]
    types:
      - completed
    branches:
      - master
env:
  NUXT_PUBLIC_SCRIPTS_GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.workflow_run && github.event.workflow_run.conclusion == 'success') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node Project
        uses: ./.github/actions/setup-node-project

      - name: Build
        run: pnpm build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./apps/angelblanco.dev/.output/public
